// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfvWI1vQOKIX8J_FMYYMfkcQpAleYNq2E',
    appId: '1:499859729466:web:7facd33366e8dacacbd903',
    messagingSenderId: '499859729466',
    projectId: 'team3-swiper-app',
    authDomain: 'team3-swiper-app.firebaseapp.com',
    storageBucket: 'team3-swiper-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1asq7e7xAD9vNTrnAP3g9KKh3ApW2f0s',
    appId: '1:499859729466:android:e947708d06bcb657cbd903',
    messagingSenderId: '499859729466',
    projectId: 'team3-swiper-app',
    storageBucket: 'team3-swiper-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW3kByjYuiqk8nafKG0ig8JxXh90XxUvY',
    appId: '1:499859729466:ios:2e6570f14d6538bdcbd903',
    messagingSenderId: '499859729466',
    projectId: 'team3-swiper-app',
    storageBucket: 'team3-swiper-app.appspot.com',
    androidClientId: '499859729466-ik655mk4e9ta9m0rrb6ov7ncbou920ig.apps.googleusercontent.com',
    iosClientId: '499859729466-4a3gkcr2a3cmbfkgq5qaseedfcqlr4mc.apps.googleusercontent.com',
    iosBundleId: 'com.example.swiperApp',
  );
}
